name: Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create .env file
      run: |
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
    
    - name: Build Docker image
      run: docker build -t receipt-qna-app .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8114:8114 -p 3000:3000 --env-file .env --name test-app receipt-qna-app
        sleep 10
        docker logs test-app
        docker stop test-app
        docker rm test-app
    
    - name: Success
      run: echo "Docker build successful!"